import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

const StyleLI: React.CSSProperties = {
  display: "flex",
  gap: "10px",
  flexDirection: "column",
  borderBottom: "1px solid #ccc",
  paddingBottom: "5px",
};
const StyleUL = { listStyle: "none" };

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Clik in the button to view the page exemple</h1>
      <Link href="profiler">
        <a className={styles.link}>View the apge</a>
      </Link>
    </div>
  );
};

export default Home;
